// RFC 0007 PR-4 — Anonymous WebAuthn challenge persistence (cookie).
//
// The PR-3 challenge helper (`src/lib/webauthn/challenge.ts`) keys the
// challenge by `userId` because the user is already signed in (during
// 2FA challenge). The PR-4 passwordless flow has no userId yet — the
// browser is going to surface a credential picker via discoverable
// authentication, and the server only learns which user is signing in
// AFTER the assertion arrives.
//
// We persist the challenge in an httpOnly cookie scoped to /api/auth/
// with a 5-minute lifetime. The cookie name is constant (only one
// passwordless flow can be in flight per browser tab), and the value
// is the random 32-byte challenge generated by `@simplewebauthn`. The
// cookie is cleared by the verify route after a successful read.

import 'server-only';

import { cookies } from 'next/headers';

const COOKIE_NAME = 'webauthn-passkey-challenge';
const TTL_SECONDS = 5 * 60;

export async function setAnonymousChallenge(challenge: string): Promise<void> {
  const jar = await cookies();
  jar.set(COOKIE_NAME, challenge, {
    httpOnly: true,
    sameSite: 'lax',
    secure: process.env.NODE_ENV === 'production',
    path: '/api/auth/webauthn/authenticate',
    maxAge: TTL_SECONDS,
  });
}

/**
 * Read + clear the anonymous challenge cookie. Returns null if no
 * cookie exists. Always clears the cookie if it does — defensive: an
 * attacker can't replay a single cookie value across multiple verify
 * attempts.
 */
export async function consumeAnonymousChallenge(): Promise<string | null> {
  const jar = await cookies();
  const value = jar.get(COOKIE_NAME)?.value;
  if (value) {
    jar.set(COOKIE_NAME, '', {
      httpOnly: true,
      sameSite: 'lax',
      secure: process.env.NODE_ENV === 'production',
      path: '/api/auth/webauthn/authenticate',
      maxAge: 0,
    });
  }
  return value ?? null;
}
